#!/bin/bash
# Standard output and error:
#SBATCH -o ./examplejob.out
#SBATCH -e ./examplejob.err
#SBATCH -D ./
#SBATCH --nodes=4
#SBATCH -J EDC_MPI
#SBATCH --mail-type=none
#SBATCH --partition=express
#SBATCH --time=00:19:59

module load mkl
module load impi

export LD_LIBRARY_PATH="$MKL_HOME/lib/intel64"


list="10 100 1000 10000"

for TIMESTEPS in $list
do
mpicxx -O2 -std=c++11 EDC_MPI.cc -DTIMESTEPS=$TIMESTEPS -L$MKL_HOME/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lm 
srun -n 128 ./a.out >log_EDC
done

