#!/bin/bash
# Standard output and error:
#SBATCH -o ./examplejob.out
#SBATCH -e ./examplejob.err
#SBATCH -D ./
#SBATCH --nodes=4
#SBATCH -J EDC_MPI
#SBATCH --mail-type=none
#SBATCH --partition=express
#SBATCH --time=00:19:59

module load mkl
module load impi

export LD_LIBRARY_PATH="$MKL_HOME/lib/intel64"


list="6.45332 12.9066 25.8133 38.7199 51.6266 64.5332"

for SIGMA_PROBE in $list
do
mpicxx -O2 -std=c++11 EDC_MPI.cc -DSIGMA_PROBE=$SIGMA_PROBE -L$MKL_HOME/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lm 
srun -n 128 ./a.out >log_EDC
done

