#!/bin/bash
# Standard output and error:
#SBATCH -o ./examplejob.out
#SBATCH -e ./examplejob.err
#SBATCH -D ./
#SBATCH --nodes=4
#SBATCH -J TESTING
#SBATCH --mail-type=none
#SBATCH --partition=express
#SBATCH --time=00:19:59

export LD_LIBRARY_PATH="$MKL_HOME/lib/intel64"

module load mkl
module load impi

mpicxx -O2 -std=c++11 ONE_BAND_ARPES.cc -L$MKL_HOME/lib/intel64 -lmkl_intel_lp64 -lmkl_core -lmkl_sequential -lm

srun -n 128  ./a.out >log_ARPES
